// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: gophkeeper/v1/secrets.proto

// Файл secrets.proto описывает хранение приватных записей пользователя.
// Полезная нагрузка (encrypted_payload) всегда зашифрована на клиенте — сервер
// её не расшифровывает (модель zero-knowledge).

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecretType — тип хранимой записи. В Спринте 1 поддержаны логин/пароль и текст;
// банковские карты и бинарные данные добавляются в Спринте 2.
type SecretType int32

const (
	SecretType_SECRET_TYPE_UNSPECIFIED    SecretType = 0
	SecretType_SECRET_TYPE_LOGIN_PASSWORD SecretType = 1
	SecretType_SECRET_TYPE_TEXT           SecretType = 2
	SecretType_SECRET_TYPE_CARD           SecretType = 3
	SecretType_SECRET_TYPE_BINARY         SecretType = 4
	SecretType_SECRET_TYPE_OTP            SecretType = 5
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "SECRET_TYPE_UNSPECIFIED",
		1: "SECRET_TYPE_LOGIN_PASSWORD",
		2: "SECRET_TYPE_TEXT",
		3: "SECRET_TYPE_CARD",
		4: "SECRET_TYPE_BINARY",
		5: "SECRET_TYPE_OTP",
	}
	SecretType_value = map[string]int32{
		"SECRET_TYPE_UNSPECIFIED":    0,
		"SECRET_TYPE_LOGIN_PASSWORD": 1,
		"SECRET_TYPE_TEXT":           2,
		"SECRET_TYPE_CARD":           3,
		"SECRET_TYPE_BINARY":         4,
		"SECRET_TYPE_OTP":            5,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_secrets_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_secrets_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretType.Descriptor instead.
func (SecretType) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secrets_proto_rawDescGZIP(), []int{0}
}

// Secret — одна приватная запись владельца.
type Secret struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  SecretType             `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.v1.SecretType" json:"type,omitempty"`
	// name — человекочитаемая метка записи (не шифруется).
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// metadata — произвольная нечувствительная метаинформация (не шифруется).
	Metadata string `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// encrypted_payload — полезная нагрузка, зашифрованная на клиенте.
	EncryptedPayload []byte `protobuf:"bytes,5,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	// version — версия записи для оптимистичной блокировки и синхронизации.
	Version   int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// deleted — тумбстон: запись удалена (для синхронизации клиентов).
	Deleted bool `protobuf:"varint,9,opt,name=deleted,proto3" json:"deleted,omitempty"`
	// revision — монотонный курсор изменения записи.
	Revision      int64 `protobuf:"varint,10,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secrets_proto_rawDescGZIP(), []int{0}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Secret) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Secret) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *Secret) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Secret) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Secret) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Secret) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Secret) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// CreateSecretRequest — создание новой записи.
type CreateSecretRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             SecretType             `protobuf:"varint,1,opt,name=type,proto3,enum=gophkeeper.v1.SecretType" json:"type,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata         string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	EncryptedPayload []byte                 `protobuf:"bytes,4,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secrets_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSecretRequest) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *CreateSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSecretRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *CreateSecretRequest) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

// GetSecretRequest — получение одной записи по идентификатору.
type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secrets_proto_rawDescGZIP(), []int{2}
}

func (x *GetSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListSecretsRequest — получение всех записей владельца.
type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secrets_proto_rawDescGZIP(), []int{3}
}

// ListSecretsResponse — список записей владельца.
type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*Secret              `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secrets_proto_rawDescGZIP(), []int{4}
}

func (x *ListSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// UpdateSecretRequest — обновление записи. Поле version содержит ожидаемую
// текущую версию для контроля конфликтов (optimistic concurrency).
type UpdateSecretRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata         string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	EncryptedPayload []byte                 `protobuf:"bytes,4,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	Version          int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secrets_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSecretRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *UpdateSecretRequest) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *UpdateSecretRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// DeleteSecretRequest — удаление записи по идентификатору.
type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secrets_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteSecretResponse — пустой ответ на удаление.
type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secrets_proto_rawDescGZIP(), []int{7}
}

// SyncRequest — запрос изменений начиная с указанного курсора-ревизии.
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceRevision int64                  `protobuf:"varint,1,opt,name=since_revision,json=sinceRevision,proto3" json:"since_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secrets_proto_rawDescGZIP(), []int{8}
}

func (x *SyncRequest) GetSinceRevision() int64 {
	if x != nil {
		return x.SinceRevision
	}
	return 0
}

// SyncResponse — изменившиеся записи (включая тумбстоны) и новый курсор.
type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*Secret              `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	Revision      int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secrets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secrets_proto_rawDescGZIP(), []int{9}
}

func (x *SyncResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *SyncResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

var File_gophkeeper_v1_secrets_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_secrets_proto_rawDesc = "" +
	"\n" +
	"\x1bgophkeeper/v1/secrets.proto\x12\rgophkeeper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x02\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12+\n" +
	"\x11encrypted_payload\x18\x05 \x01(\fR\x10encryptedPayload\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\adeleted\x18\t \x01(\bR\adeleted\x12\x1a\n" +
	"\brevision\x18\n" +
	" \x01(\x03R\brevision\"\xa1\x01\n" +
	"\x13CreateSecretRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12+\n" +
	"\x11encrypted_payload\x18\x04 \x01(\fR\x10encryptedPayload\"\"\n" +
	"\x10GetSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12ListSecretsRequest\"F\n" +
	"\x13ListSecretsResponse\x12/\n" +
	"\asecrets\x18\x01 \x03(\v2\x15.gophkeeper.v1.SecretR\asecrets\"\x9c\x01\n" +
	"\x13UpdateSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12+\n" +
	"\x11encrypted_payload\x18\x04 \x01(\fR\x10encryptedPayload\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\"%\n" +
	"\x13DeleteSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteSecretResponse\"4\n" +
	"\vSyncRequest\x12%\n" +
	"\x0esince_revision\x18\x01 \x01(\x03R\rsinceRevision\"[\n" +
	"\fSyncResponse\x12/\n" +
	"\asecrets\x18\x01 \x03(\v2\x15.gophkeeper.v1.SecretR\asecrets\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision*\xa2\x01\n" +
	"\n" +
	"SecretType\x12\x1b\n" +
	"\x17SECRET_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSECRET_TYPE_LOGIN_PASSWORD\x10\x01\x12\x14\n" +
	"\x10SECRET_TYPE_TEXT\x10\x02\x12\x14\n" +
	"\x10SECRET_TYPE_CARD\x10\x03\x12\x16\n" +
	"\x12SECRET_TYPE_BINARY\x10\x04\x12\x13\n" +
	"\x0fSECRET_TYPE_OTP\x10\x052\xbc\x03\n" +
	"\x0eSecretsService\x12C\n" +
	"\x06Create\x12\".gophkeeper.v1.CreateSecretRequest\x1a\x15.gophkeeper.v1.Secret\x12M\n" +
	"\x04List\x12!.gophkeeper.v1.ListSecretsRequest\x1a\".gophkeeper.v1.ListSecretsResponse\x12=\n" +
	"\x03Get\x12\x1f.gophkeeper.v1.GetSecretRequest\x1a\x15.gophkeeper.v1.Secret\x12C\n" +
	"\x06Update\x12\".gophkeeper.v1.UpdateSecretRequest\x1a\x15.gophkeeper.v1.Secret\x12Q\n" +
	"\x06Delete\x12\".gophkeeper.v1.DeleteSecretRequest\x1a#.gophkeeper.v1.DeleteSecretResponse\x12?\n" +
	"\x04Sync\x12\x1a.gophkeeper.v1.SyncRequest\x1a\x1b.gophkeeper.v1.SyncResponseB0Z.github.com/warenikov/gophkeeper/internal/pb;pbb\x06proto3"

var (
	file_gophkeeper_v1_secrets_proto_rawDescOnce sync.Once
	file_gophkeeper_v1_secrets_proto_rawDescData []byte
)

func file_gophkeeper_v1_secrets_proto_rawDescGZIP() []byte {
	file_gophkeeper_v1_secrets_proto_rawDescOnce.Do(func() {
		file_gophkeeper_v1_secrets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_secrets_proto_rawDesc), len(file_gophkeeper_v1_secrets_proto_rawDesc)))
	})
	return file_gophkeeper_v1_secrets_proto_rawDescData
}

var file_gophkeeper_v1_secrets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gophkeeper_v1_secrets_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gophkeeper_v1_secrets_proto_goTypes = []any{
	(SecretType)(0),               // 0: gophkeeper.v1.SecretType
	(*Secret)(nil),                // 1: gophkeeper.v1.Secret
	(*CreateSecretRequest)(nil),   // 2: gophkeeper.v1.CreateSecretRequest
	(*GetSecretRequest)(nil),      // 3: gophkeeper.v1.GetSecretRequest
	(*ListSecretsRequest)(nil),    // 4: gophkeeper.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),   // 5: gophkeeper.v1.ListSecretsResponse
	(*UpdateSecretRequest)(nil),   // 6: gophkeeper.v1.UpdateSecretRequest
	(*DeleteSecretRequest)(nil),   // 7: gophkeeper.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),  // 8: gophkeeper.v1.DeleteSecretResponse
	(*SyncRequest)(nil),           // 9: gophkeeper.v1.SyncRequest
	(*SyncResponse)(nil),          // 10: gophkeeper.v1.SyncResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_gophkeeper_v1_secrets_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.v1.Secret.type:type_name -> gophkeeper.v1.SecretType
	11, // 1: gophkeeper.v1.Secret.created_at:type_name -> google.protobuf.Timestamp
	11, // 2: gophkeeper.v1.Secret.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: gophkeeper.v1.CreateSecretRequest.type:type_name -> gophkeeper.v1.SecretType
	1,  // 4: gophkeeper.v1.ListSecretsResponse.secrets:type_name -> gophkeeper.v1.Secret
	1,  // 5: gophkeeper.v1.SyncResponse.secrets:type_name -> gophkeeper.v1.Secret
	2,  // 6: gophkeeper.v1.SecretsService.Create:input_type -> gophkeeper.v1.CreateSecretRequest
	4,  // 7: gophkeeper.v1.SecretsService.List:input_type -> gophkeeper.v1.ListSecretsRequest
	3,  // 8: gophkeeper.v1.SecretsService.Get:input_type -> gophkeeper.v1.GetSecretRequest
	6,  // 9: gophkeeper.v1.SecretsService.Update:input_type -> gophkeeper.v1.UpdateSecretRequest
	7,  // 10: gophkeeper.v1.SecretsService.Delete:input_type -> gophkeeper.v1.DeleteSecretRequest
	9,  // 11: gophkeeper.v1.SecretsService.Sync:input_type -> gophkeeper.v1.SyncRequest
	1,  // 12: gophkeeper.v1.SecretsService.Create:output_type -> gophkeeper.v1.Secret
	5,  // 13: gophkeeper.v1.SecretsService.List:output_type -> gophkeeper.v1.ListSecretsResponse
	1,  // 14: gophkeeper.v1.SecretsService.Get:output_type -> gophkeeper.v1.Secret
	1,  // 15: gophkeeper.v1.SecretsService.Update:output_type -> gophkeeper.v1.Secret
	8,  // 16: gophkeeper.v1.SecretsService.Delete:output_type -> gophkeeper.v1.DeleteSecretResponse
	10, // 17: gophkeeper.v1.SecretsService.Sync:output_type -> gophkeeper.v1.SyncResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_secrets_proto_init() }
func file_gophkeeper_v1_secrets_proto_init() {
	if File_gophkeeper_v1_secrets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_secrets_proto_rawDesc), len(file_gophkeeper_v1_secrets_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_v1_secrets_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_secrets_proto_depIdxs,
		EnumInfos:         file_gophkeeper_v1_secrets_proto_enumTypes,
		MessageInfos:      file_gophkeeper_v1_secrets_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_secrets_proto = out.File
	file_gophkeeper_v1_secrets_proto_goTypes = nil
	file_gophkeeper_v1_secrets_proto_depIdxs = nil
}
